version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projet_ter_m1_miage
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DB_HOST: db
      DB_NAME: projet_ter_m1_miage
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
    ports:
      - "8001:8001"

  postit-service:
    build:
      context: ./postit-service
      dockerfile: Dockerfile
    container_name: postit-service
    environment:
      DB_HOST: db
      DB_NAME: projet_ter_m1_miage
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
    ports:
      - "8002:8002"

  front-service:
    build:
      context: ./front-service
      dockerfile: Dockerfile
    container_name: front-service
    environment:
      DB_HOST: db
      DB_NAME: projet_ter_m1_miage
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
      - user-service
      - postit-service
    ports:
      - "8080:80"

volumes:
  db_data:
