name: CI/CD Pipeline with Minikube

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ROUSMANE }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push front-service Docker image
      run: |
        docker build -t ${{ secrets.ROUSMANE }}/front-service:latest ./front-service
        docker push ${{ secrets.ROUSMANE }}/front-service:latest

    - name: Build and push user-service Docker image
      run: |
        docker build -t ${{ secrets.ROUSMANE }}/user-service:latest ./user-service
        docker push ${{ secrets.ROUSMANE }}/user-service:latest

    - name: Build and push postit-service Docker image
      run: |
        docker build -t ${{ secrets.ROUSMANE }}/postit-service:latest ./postit-service
        docker push ${{ secrets.ROUSMANE }}/postit-service:latest

  deploy-minikube:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
      with:
        driver: docker

    - name: Configure Docker for Minikube
      run: |
        eval $(minikube -p minikube docker-env)

    - name: Load images into Minikube
      run: |
        minikube image load ${{ secrets.ROUSMANE }}/front-service:latest
        minikube image load ${{ secrets.ROUSMANE }}/user-service:latest
        minikube image load ${{ secrets.ROUSMANE }}/postit-service:latest

    - name: Create Kubernetes namespace
      run: |
        kubectl create namespace postit-projet || echo "Namespace already exists"

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/mysql-deployment.yaml -n postit-projet
        kubectl apply -f kubernetes/user-deployment.yaml -n postit-projet
        kubectl apply -f kubernetes/postit-deployment.yaml -n postit-projet
        kubectl apply -f kubernetes/front-deployment.yaml -n postit-projet
        kubectl apply -f kubernetes/ingress.yaml -n postit-projet

    - name: Check Kubernetes resources
      run: |
        kubectl get pods -n postit-projet
        kubectl get services -n postit-projet

    - name: Test Application
      run: |
        echo "Testing application..."
        kubectl get ingress -n postit-projet
