name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  docker-build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ROUSMANE }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push front-service Docker image
      run: |
        docker build -t ${{ secrets.ROUSMANE }}/front-service:latest ./front-service
        docker push ${{ secrets.ROUSMANE }}/front-service:latest

    - name: Build and push user-service Docker image
      run: |
        docker build -t ${{ secrets.ROUSMANE }}/user-service:latest ./user-service
        docker push ${{ secrets.ROUSMANE }}/user-service:latest

    - name: Build and push postit-service Docker image
      run: |
        docker build -t ${{ secrets.ROUSMANE }}/postit-service:latest ./postit-service
        docker push ${{ secrets.ROUSMANE }}/postit-service:latest

  deploy-k8s:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/mysql-deployment.yaml
        kubectl apply -f kubernetes/user-deployment.yaml
        kubectl apply -f kubernetes/postit-deployment.yaml
        kubectl apply -f kubernetes/front-deployment.yaml
        kubectl apply -f kubernetes/ingress.yaml
